### ISSUE TITLE
Run PFASPrioritization issue

### ISSUE THREAD

**Issue by nmacorpslaberca** [JonZwe/PFAScreen#10]
Hi,
I am currently running some experiment on a LC-Q-Exactive instrument for PFAS suspect screening analyses. 
I used a Fullscan->ddMS2 experiment with top 5 fragmentation, and step collision energy.
I converted my files with msConvert using : peakPicking vendor (msLevel 1-2) and titleMaker.

When using PFAScreen "Run FeatureFinding", everything went fine but when I use the prioritization with default parameters I have the following error message:

  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 5, saw 12

Do you have any idea why ? Is it and issue with my mzML conversion ?

Best regards,

Nicolas

**Comment by JonZwe** [comment]
Hi Nicolas, 
thanks for reporting your issue! Since it happens during the prioritization step, I would assume that the mzML file it not the problem, since this is not used in the feature prioritization step (only for preprocessing and plotting). At the first glance it looks like this error might appear during CSV reading/writing of the table (or maybe the suspect list/fragment list), however I cannot see the line number in your error message. Would you be able to send me a file link with this particular mzML file, then I would try to figure out what happens.
From this error message alone, I am not sure whether I can fix it!
Best,
Jonathan

**Comment by nmacorpslaberca** [comment]
Hi Jonathan,

Here is a link to download the *.mzML files and in case you want to work on the conversion, I also added the *.raw files.

https://filesender.renater.fr/?s=download&token=1a2d9520-6397-48d2-914b-852c4dcdf5c6 

Thank you for your time and help!

Best regards, 
Nicolas

**Comment by JonZwe** [comment]
Dear Nicolas,
thanks for the files! "Unfortunately", in my case everything works perfectly with your provided files :D. Several PFAS classes are detected in the QC. Again, from the error message it seems that the writing/reading of your CSV files does not work properly. Have you changed something in these files or were some files open during running PFAScreen? This could be the reason of the issue. Since the error occurred with Pandas, you could also try to update Pandas manually by using the command prompt and typing "pip install --upgrade pandas". It would also be a try worth to comment out the code lines that do the CSV stuff (if the Excel file if also fine for you).
Other than that, with the present information, I cannot really help you. Just let me know if you can provide me more info, also from your error message, so that we know the line number. 
Best,
Jonathan

**Comment by nmacorpslaberca** [comment]
Dear Jonathan,

This is kind of weird but it seems that the computer I used had an issue somehow. It works fine indeed when trying elsewhere. 

Thanks for looking into this anyway ! :)

Best regards, 

Nicolas
