### ISSUE TITLE
Example Files for Testing PFAScreen Installation

### ISSUE THREAD

**Issue by cfarm6** [JonZwe/PFAScreen#11]
We are starting to work on getting an installation of PFAScreen running. Before testing with our data, we wanted to test against some existing data, potentially the data from the tutorial video, to make sure the program runs for us before working with our data. Is it possible to have example files made available for testing the software? This may be helpful for future works to the software to have a common test set of files to work with to have verifiable results.

**Comment by JonZwe** [comment]
Dear Carson,
thanks for the comment. I cannot share the file from the tutorial video, however, find attached an mzML file from a PFAS standard mixture measured on our QTOF instrument via this file link https://file.io/35xdLHWjElKr. With this you can check in the results table whether e.g., C4-C10 PFCAs and C4-C10 PFSAs correctly detected in the feature detection step. We don't have a real test scenario for the code. Generally, however, I would recommend you to test the code with your own files (since every instrument produces unique data) via a reference standard to check if the correct features are detected and the parameters are suitable.
I hope this helps!
Best,
Jonathan

**Comment by cfarm6** [comment]
Jonathan, 
Thank you. That helps with getting this setup for us. 
Best, 
Carson
